
import Foundation

enum Localization {
    
    static let defaultMode: String = NSLocalizedString("defaultMode", comment: "")
    static let couples: String = NSLocalizedString("couples", comment: "")
    static let family: String = NSLocalizedString("family", comment: "")
    static let favorites: String = NSLocalizedString("favorites", comment: "")
    static let created: String = NSLocalizedString("created", comment: "")
    static let generateAction: String = NSLocalizedString("generateAction", comment: "")
    static let cards: String = NSLocalizedString("cards", comment: "")
    static let card: String = NSLocalizedString("card", comment: "")
    static let goBack: String = NSLocalizedString("goBack", comment: "")
    static let whatIs: String = NSLocalizedString("whatIs", comment: "")
    static let aboutTheApp: String = NSLocalizedString("aboutTheApp", comment: "")
    static let share: String = NSLocalizedString("share", comment: "")
    static let review: String = NSLocalizedString("review", comment: "")
    static let terms: String = NSLocalizedString("terms", comment: "")
    static let privacy: String = NSLocalizedString("privacy", comment: "")
    static let contact: String = NSLocalizedString("contact", comment: "")
    static let credential: String = NSLocalizedString("credential", comment: "")
    static let version: String = NSLocalizedString("version", comment: "")
    static let createPack: String = NSLocalizedString("createPack", comment: "")
    static let createCard: String = NSLocalizedString("createCard", comment: "")
    static let name: String = NSLocalizedString("name", comment: "")
    static let question: String = NSLocalizedString("question", comment: "")
    static let create: String = NSLocalizedString("create", comment: "")
    static let thatIsAll: String = NSLocalizedString("thatIsAll", comment: "")
    static let prompt: String = NSLocalizedString("prompt", comment: "")
    static let generateNoun: String = NSLocalizedString("generateNoun", comment: "")
    static let clear: String = NSLocalizedString("clear", comment: "")
    static let whatIs1Header: String = NSLocalizedString("whatIs1Header", comment: "")
    static let whatIs1Name: String = NSLocalizedString("whatIs1Name", comment: "")
    static let whatIs2Header: String = NSLocalizedString("whatIs2Header", comment: "")
    static let whatIs2Name: String = NSLocalizedString("whatIs2Name", comment: "")
    static let whatIs3Header: String = NSLocalizedString("whatIs3Header", comment: "")
    static let whatIs3Name: String = NSLocalizedString("whatIs3Name", comment: "")
    static let whatIs4Header: String = NSLocalizedString("whatIs4Header", comment: "")
    static let whatIs4Name: String = NSLocalizedString("whatIs4Name", comment: "")
    static let deleting: String = NSLocalizedString("deleting", comment: "")
    static let delete: String = NSLocalizedString("delete", comment: "")
    static let cancel: String = NSLocalizedString("cancel", comment: "")
    static let perfect: String = NSLocalizedString("perfect", comment: "")
    static let empty: String = NSLocalizedString("empty", comment: "")
    
}
