# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'hearttalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hearttalk
  pod 'RealmSwift'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseRemoteConfig'

end

target 'hearttalkWidgetExtensionExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hearttalk
  pod 'RealmSwift'

end
